import type { PullRequestImpact } from "./types";

function cell(value: string | number): string {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("\n", " ");
}

function code(value: string): string {
  return `\`${value.replaceAll("`", "'").replaceAll("\n", " ")}\``;
}

export function pullRequestReportFilename(report: PullRequestImpact): string {
  return `regora-pr-${report.pull_request.number}-review.md`;
}

export function buildPullRequestImpactMarkdown(report: PullRequestImpact): string {
  const { pull_request: pullRequest, summary } = report;
  const lines = [
    "# Regora pull request review",
    "",
    `## [PR #${pullRequest.number}: ${cell(pullRequest.title)}](${pullRequest.url})`,
    "",
    `${code(pullRequest.base)} → ${code(pullRequest.head)} · ${cell(pullRequest.state)}`,
    "",
    `**Highest risk: ${cell(summary.risk)} (${summary.score}/100)**`,
    "",
    "| Metric | Value |",
    "| --- | ---: |",
    `| Changed files | ${summary.files_changed} |`,
    `| Changed symbols | ${summary.symbols_changed} |`,
    `| Affected files | ${summary.affected_files} |`,
    `| Affected API routes | ${summary.affected_endpoints} |`,
    "",
    "## Review agent",
    "",
    `**${cell(report.review.status)}: ${cell(report.review.headline)}**`,
    "",
    report.review.summary,
    "",
    "### Findings",
    "",
    ...(report.review.findings.length
      ? report.review.findings.map(
          (finding) =>
            `- **${cell(finding.severity.toUpperCase())}: ${cell(finding.title)}** — ${cell(finding.detail)} (${code(`${finding.file}:${finding.start_line}`)})`,
        )
      : ["- No mapped impact findings."]),
    "",
    "### Review checklist",
    "",
    ...report.review.checklist.map(
      (item) =>
        `- [${item.status === "pass" ? "x" : " "}] **${cell(item.label)}:** ${cell(item.detail)}`,
    ),
    "",
    "### Related tests",
    "",
    ...([...new Set([...report.review.related_tests, ...report.review.changed_test_files])].length
      ? [...new Set([...report.review.related_tests, ...report.review.changed_test_files])].map(
          (path) => `- ${code(path)}`,
        )
      : ["- No connected or changed test files were identified."]),
    "",
    "### Coverage signals",
    "",
    ...(report.review.coverage_gaps.length
      ? report.review.coverage_gaps.map(
          (gap) => `- ${code(gap.symbol)} in ${code(gap.file)}: ${cell(gap.reason)}`,
        )
      : ["- Every mapped changed symbol has a statically connected test file."]),
    "",
    "## Highest impact symbols",
    "",
  ];

  if (report.impacts.length) {
    lines.push(
      "| Symbol | Type | Location | Risk | Score | Blast radius | Affected files | API routes |",
      "| --- | --- | --- | --- | ---: | ---: | ---: | ---: |",
      ...report.impacts.map(
        (impact) =>
          `| ${code(impact.node.name)} | ${cell(impact.node.type)} | ${code(impact.node.file_path)} | ${cell(impact.risk)} | ${impact.score} | ${impact.blast_radius} | ${impact.affected_files.length} | ${impact.affected_endpoints.length} |`,
      ),
    );
  } else {
    lines.push("No changed symbols from this pull request exist in the current index.");
  }

  lines.push(
    "",
    "## Changed files",
    "",
    "| File | Status | Additions | Deletions | Mapped symbols |",
    "| --- | --- | ---: | ---: | ---: |",
    ...report.files.map(
      (file) =>
        `| ${code(file.path)} | ${cell(file.status)} | +${file.additions} | -${file.deletions} | ${file.symbols.length} |`,
    ),
  );

  if (report.unmatched_files.length) {
    lines.push(
      "",
      "## Files without indexed symbols",
      "",
      ...report.unmatched_files.map((file) => `- ${code(file)}`),
    );
  }
  if (report.truncated) {
    lines.push("", "> This analysis was truncated by Regora's safety limits.");
  }
  lines.push("", `> ${report.caveat}`, "", "Generated by the Regora PR Review Agent.", "");
  return lines.join("\n");
}
